# Importing **numpy** Library

In [5]:
import numpy as n

In [6]:
dir(n)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

## Creating an array and diaplaying

In [7]:
l=[5,7,45,77,66,90]
l

[5, 7, 45, 77, 66, 90]

In [8]:
arr=n.array([23,43,57,84,1,13,31])
print(arr)

[23 43 57 84  1 13 31]


In [9]:
a2=n.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating 1D arrays with **all elements** 0 or 1

In [11]:
a=n.zeros(7,dtype=int)
print(a)

[0 0 0 0 0 0 0]


In [12]:
a3=n.ones(10)
a3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## _Identity_ Matrix

In [13]:
a4=n.eye(5,dtype=int)
print(a4)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## Creating 2D arrays with **all elements** 0 or 1

In [14]:
ar1=n.zeros((2,3),dtype=int)
ar1

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
ar2=n.ones((3,4),dtype=int)
ar2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Array creating within a **range** 

In [16]:
ar4=n.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
ar5=n.arange(-3,-19,-2)
ar5

array([ -3,  -5,  -7,  -9, -11, -13, -15, -17])

In [18]:
ar6=n.arange(1,15,4)
ar6

array([ 1,  5,  9, 13])

## An Arithmetic Progression **_(A.P)_** type array

In [19]:
ar7=n.linspace(1,10,6)
print(ar7)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [20]:
ar8=n.linspace(-3,-9,5)
ar8

array([-3. , -4.5, -6. , -7.5, -9. ])

## Creating an array with all elements equal

In [21]:
ar9=n.full(5,2)
ar9

array([2, 2, 2, 2, 2])

In [22]:
arr1=n.full((3,3),4)
arr1

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## Creating **Random** Array

In [23]:
r1=n.random.rand(4,4)
r1

array([[0.40890271, 0.67419609, 0.03470614, 0.18429905],
       [0.21305029, 0.34828944, 0.1420194 , 0.43632706],
       [0.36300734, 0.4425836 , 0.03339254, 0.81404834],
       [0.42396775, 0.80085784, 0.37527738, 0.65665139]])

In [24]:
r2=n.random.rand(5)
r2

array([0.16845984, 0.58148817, 0.57790662, 0.39819448, 0.85472032])

In [25]:
r3=n.random.randint(5)
r3

3

In [26]:
r4=n.random.randint(3,19,7)
r4

array([17, 13,  5, 13,  6, 14,  6], dtype=int32)

In [27]:
r5=n.random.randint(3,9,(3,3))
r5

array([[7, 5, 8],
       [7, 5, 4],
       [7, 8, 5]], dtype=int32)

## Indexing Array

In [28]:
a=n.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
print(a[0])

1


In [30]:
print(a[4])

5


In [31]:
print(a[-1])

9


In [32]:
print(a[-6])

4


In [33]:
a2=n.random.randint(1,10,(3,3))
a2

array([[5, 1, 9],
       [5, 6, 6],
       [1, 1, 3]], dtype=int32)

In [34]:
print(a2[0][1])

1


In [35]:
print(a2[2][1])

1


In [36]:
print(a2[0,1])

1


In [37]:
print(a2[2,0])

1


## Slicing Of array

In [38]:
a=n.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
a[0:5]

array([3, 4, 5, 6, 7])

In [40]:
a[-3:-9:-1]

array([12, 11, 10,  9,  8,  7])

In [41]:
a[2:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
a[0::3]

array([ 3,  6,  9, 12])

In [43]:
a[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

In [44]:
a2=n.random.randint(1,10,(3,3))
a2

array([[3, 5, 9],
       [2, 9, 3],
       [8, 9, 9]], dtype=int32)

In [45]:
a2[0:2,2]

array([9, 3], dtype=int32)

In [46]:
a2[0:,2]

array([9, 3, 9], dtype=int32)

In [47]:
a2[1,0:2]

array([2, 9], dtype=int32)

In [48]:
a2[:,:]

array([[3, 5, 9],
       [2, 9, 3],
       [8, 9, 9]], dtype=int32)

In [49]:
a2[0:,1:]

array([[5, 9],
       [9, 3],
       [9, 9]], dtype=int32)

## Shape , Size and Datatype of Array

In [50]:
a=n.random.randint(1,50,9)
a

array([41, 12, 29, 14, 41, 25, 44, 40, 11], dtype=int32)

In [51]:
print(a.shape)

(9,)


In [52]:
a2=n.random.randint(1,20,(4,4))
a2

array([[ 5, 18, 19,  7],
       [10,  8,  2, 14],
       [13, 11, 19, 12],
       [ 8,  3,  1,  2]], dtype=int32)

In [53]:
print(a2.shape)

(4, 4)


In [54]:
a.size

9

In [55]:
a2.size

16

In [56]:
a.dtype

dtype('int32')

In [57]:
a2.dtype

dtype('int32')

## Mathematical Operations on Arrays

In [58]:
a1=n.random.randint(11,25,6)
a2=n.arange(1,7)

In [59]:
a1

array([24, 12, 22, 21, 13, 15], dtype=int32)

In [60]:
a2


array([1, 2, 3, 4, 5, 6])

In [61]:
a1+a2


array([25, 14, 25, 25, 18, 21])

In [62]:
a1-a2

array([23, 10, 19, 17,  8,  9])

In [63]:
a1*a2

array([24, 24, 66, 84, 65, 90])

In [64]:
a1/a2

array([24.        ,  6.        ,  7.33333333,  5.25      ,  2.6       ,
        2.5       ])

In [65]:
a3=n.array([9,16,25,36,49,64,81])
n.sqrt(a3)

array([3., 4., 5., 6., 7., 8., 9.])

In [66]:
p=n.floor([11.2,7,3.9,7.86,3.54])
p

array([11.,  7.,  3.,  7.,  3.])

In [67]:
q=n.ceil([11.2,7,3.9,7.86,3.54])
q

array([12.,  7.,  4.,  8.,  4.])